package com.wap.entity;

import java.util.Date;

public class OrderOrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.store_id
     *
     * @mbggenerated
     */
    private Long storeId;
    private Long operId;

    public Long getOperId() {
		return operId;
	}

	public void setOperId(Long operId) {
		this.operId = operId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.desk_id
     *
     * @mbggenerated
     */
    private Long deskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.person_num
     *
     * @mbggenerated
     */
    private Integer personNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.order_way
     *
     * @mbggenerated
     */
    private Integer orderWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.order_amount
     *
     * @mbggenerated
     */
    private Integer orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus; 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.pay_way
     *
     * @mbggenerated
     */
    private Integer payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.pay_order_id
     *
     * @mbggenerated
     */
    private Long payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_order_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.id
     *
     * @return the value of order_order_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.id
     *
     * @param id the value for order_order_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.merchant_id
     *
     * @return the value of order_order_info.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.merchant_id
     *
     * @param merchantId the value for order_order_info.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.store_id
     *
     * @return the value of order_order_info.store_id
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.store_id
     *
     * @param storeId the value for order_order_info.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.desk_id
     *
     * @return the value of order_order_info.desk_id
     *
     * @mbggenerated
     */
    public Long getDeskId() {
        return deskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.desk_id
     *
     * @param deskId the value for order_order_info.desk_id
     *
     * @mbggenerated
     */
    public void setDeskId(Long deskId) {
        this.deskId = deskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.customer_id
     *
     * @return the value of order_order_info.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.customer_id
     *
     * @param customerId the value for order_order_info.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.person_num
     *
     * @return the value of order_order_info.person_num
     *
     * @mbggenerated
     */
    public Integer getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.person_num
     *
     * @param personNum the value for order_order_info.person_num
     *
     * @mbggenerated
     */
    public void setPersonNum(Integer personNum) {
        this.personNum = personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.create_time
     *
     * @return the value of order_order_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.create_time
     *
     * @param createTime the value for order_order_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.order_way
     *
     * @return the value of order_order_info.order_way
     *
     * @mbggenerated
     */
    public Integer getOrderWay() {
        return orderWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.order_way
     *
     * @param orderWay the value for order_order_info.order_way
     *
     * @mbggenerated
     */
    public void setOrderWay(Integer orderWay) {
        this.orderWay = orderWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.order_amount
     *
     * @return the value of order_order_info.order_amount
     *
     * @mbggenerated
     */
    public Integer getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.order_amount
     *
     * @param orderAmount the value for order_order_info.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(Integer orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.order_status
     *
     * @return the value of order_order_info.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.order_status
     *
     * @param orderStatus the value for order_order_info.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.pay_way
     *
     * @return the value of order_order_info.pay_way
     *
     * @mbggenerated
     */
    public Integer getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.pay_way
     *
     * @param payWay the value for order_order_info.pay_way
     *
     * @mbggenerated
     */
    public void setPayWay(Integer payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.pay_order_id
     *
     * @return the value of order_order_info.pay_order_id
     *
     * @mbggenerated
     */
    public Long getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.pay_order_id
     *
     * @param payOrderId the value for order_order_info.pay_order_id
     *
     * @mbggenerated
     */
    public void setPayOrderId(Long payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_order_info.remark
     *
     * @return the value of order_order_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_order_info.remark
     *
     * @param remark the value for order_order_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}