package com.wap.dao;

import java.util.List;

import com.wap.entity.OrderOrderInfo;

public interface OrderOrderInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_order_info int deleteByPrimaryKey(Long id);
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_order_info int insert(OrderOrderInfo record);
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_order_info int insertSelective(OrderOrderInfo
	 * record);
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_order_info OrderOrderInfo
	 * selectByPrimaryKey(Long id);
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_order_info int
	 * updateByPrimaryKeySelective(OrderOrderInfo record);
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_order_info int
	 * updateByPrimaryKey(OrderOrderInfo record);
	 * 
	 * @mbggenerated
	 */

	List<OrderOrderInfo> getAllOrdering();

	List<Long> getorder();

}