package com.wap.dao;

import com.wap.entity.OrderCustomer;

public interface OrderCustomerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_customer
	 * 
	 * int deleteByPrimaryKey(Long id);
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_customer
	 * 
	 * int insert(OrderCustomer record);
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_customer
	 * 
	 * int insertSelective(OrderCustomer record);
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_customer
	 * 
	 * OrderCustomer selectByPrimaryKey(Long id);
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_customer
	 * 
	 * int updateByPrimaryKeySelective(OrderCustomer record);
	 */

	/**
	 * Login
	 * 
	 * @return
	 */
	OrderCustomer loginWap(String mobile, String password);

	/**
	 * x修改密码
	 * @return
	 */
	int ChageWapPwd();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_customer
	 * 
	 * int updateByPrimaryKey(OrderCustomer record);
	 */

}