package com.wap.dao;

import com.wap.entity.OrderOrderDetail;

public interface OrderOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order_detail
     *
     * @mbggenerated
     */
    int insert(OrderOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order_detail
     *
     * @mbggenerated
     */
    OrderOrderDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderOrderDetail record);
    
    
    
}