package com.gjcm.dao;

import com.gjcm.entity.HFOrderVersion;

public interface HFOrderVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifuorder_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifuorder_version
     *
     * @mbggenerated
     */
    int insert(HFOrderVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifuorder_version
     *
     * @mbggenerated
     */
    int insertSelective(HFOrderVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifuorder_version
     *
     * @mbggenerated
     */
    HFOrderVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifuorder_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HFOrderVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifuorder_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HFOrderVersion record);
    /**
     * 验证version
     * @return
     */
    HFOrderVersion selectHForderVersion();
}