package com.gjcm.dao;

import java.util.Date;
import java.util.HashMap;

import com.gjcm.entity.UserDevice;

public interface UserDeviceMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long umengid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 * 
	 * @mbggenerated
	 */
	int insert(UserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 * 
	 * @mbggenerated
	 */
	int insertSelective(UserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 * 
	 * @mbggenerated
	 */
	UserDevice selectByPrimaryKey(Long umengid);

	/**
	 * 
	 * @return
	 */
	int updateUserlogin(HashMap<String, Object> hashmap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserDevice record);
}