package com.gjcm.entity;

import java.util.Date;

public class AppVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.android_version
     *
     * @mbggenerated
     */
    private String androidVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.apk_url
     *
     * @mbggenerated
     */
    private String apkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.ipa_url
     *
     * @mbggenerated
     */
    private String ipaUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.android_version_name
     *
     * @mbggenerated
     */
    private String androidVersionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.android_version
     *
     * @return the value of app_version.android_version
     *
     * @mbggenerated
     */
    public String getAndroidVersion() {
        return androidVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.android_version
     *
     * @param androidVersion the value for app_version.android_version
     *
     * @mbggenerated
     */
    public void setAndroidVersion(String androidVersion) {
        this.androidVersion = androidVersion == null ? null : androidVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.apk_url
     *
     * @return the value of app_version.apk_url
     *
     * @mbggenerated
     */
    public String getApkUrl() {
        return apkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.apk_url
     *
     * @param apkUrl the value for app_version.apk_url
     *
     * @mbggenerated
     */
    public void setApkUrl(String apkUrl) {
        this.apkUrl = apkUrl == null ? null : apkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.update_time
     *
     * @return the value of app_version.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.update_time
     *
     * @param updateTime the value for app_version.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.create_time
     *
     * @return the value of app_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.create_time
     *
     * @param createTime the value for app_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.ipa_url
     *
     * @return the value of app_version.ipa_url
     *
     * @mbggenerated
     */
    public String getIpaUrl() {
        return ipaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.ipa_url
     *
     * @param ipaUrl the value for app_version.ipa_url
     *
     * @mbggenerated
     */
    public void setIpaUrl(String ipaUrl) {
        this.ipaUrl = ipaUrl == null ? null : ipaUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.android_version_name
     *
     * @return the value of app_version.android_version_name
     *
     * @mbggenerated
     */
    public String getAndroidVersionName() {
        return androidVersionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.android_version_name
     *
     * @param androidVersionName the value for app_version.android_version_name
     *
     * @mbggenerated
     */
    public void setAndroidVersionName(String androidVersionName) {
        this.androidVersionName = androidVersionName == null ? null : androidVersionName.trim();
    }
}