package com.gjcm.entity;

import java.util.Date;

public class HFOrderVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.apporder_code
     *
     * @mbggenerated
     */
    private String apporderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.orderapk_url
     *
     * @mbggenerated
     */
    private String orderapkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.ipad_url
     *
     * @mbggenerated
     */
    private String ipadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifuorder_version.apporder_version_name
     *
     * @mbggenerated
     */
    private String apporderVersionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.id
     *
     * @return the value of huifuorder_version.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.id
     *
     * @param id the value for huifuorder_version.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.apporder_code
     *
     * @return the value of huifuorder_version.apporder_code
     *
     * @mbggenerated
     */
    public String getApporderCode() {
        return apporderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.apporder_code
     *
     * @param apporderCode the value for huifuorder_version.apporder_code
     *
     * @mbggenerated
     */
    public void setApporderCode(String apporderCode) {
        this.apporderCode = apporderCode == null ? null : apporderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.orderapk_url
     *
     * @return the value of huifuorder_version.orderapk_url
     *
     * @mbggenerated
     */
    public String getOrderapkUrl() {
        return orderapkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.orderapk_url
     *
     * @param orderapkUrl the value for huifuorder_version.orderapk_url
     *
     * @mbggenerated
     */
    public void setOrderapkUrl(String orderapkUrl) {
        this.orderapkUrl = orderapkUrl == null ? null : orderapkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.update_time
     *
     * @return the value of huifuorder_version.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.update_time
     *
     * @param updateTime the value for huifuorder_version.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.create_time
     *
     * @return the value of huifuorder_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.create_time
     *
     * @param createTime the value for huifuorder_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.ipad_url
     *
     * @return the value of huifuorder_version.ipad_url
     *
     * @mbggenerated
     */
    public String getIpadUrl() {
        return ipadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.ipad_url
     *
     * @param ipadUrl the value for huifuorder_version.ipad_url
     *
     * @mbggenerated
     */
    public void setIpadUrl(String ipadUrl) {
        this.ipadUrl = ipadUrl == null ? null : ipadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifuorder_version.apporder_version_name
     *
     * @return the value of huifuorder_version.apporder_version_name
     *
     * @mbggenerated
     */
    public String getApporderVersionName() {
        return apporderVersionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifuorder_version.apporder_version_name
     *
     * @param apporderVersionName the value for huifuorder_version.apporder_version_name
     *
     * @mbggenerated
     */
    public void setApporderVersionName(String apporderVersionName) {
        this.apporderVersionName = apporderVersionName == null ? null : apporderVersionName.trim();
    }
}