package com.gjcm.entity;

import java.util.Date;

public class UserDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.umengid
     *
     * @mbggenerated
     */
    private Long umengid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.storeid
     *
     * @mbggenerated
     */
    private Long storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.usertoken
     *
     * @mbggenerated
     */
    private String usertoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.devicetoken
     *
     * @mbggenerated
     */
    private String devicetoken;
    
    /**
     * 登录的用户名
     */
    private String loginusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.appversion
     *
     * @mbggenerated
     */
    private String appversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.logintime
     *
     * @mbggenerated
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.devicemac
     *
     * @mbggenerated
     */
    private String devicemac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.deviceimei
     *
     * @mbggenerated
     */
    private String deviceimei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.devicenote
     *
     * @mbggenerated
     */
    private String devicenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.umengid
     *
     * @return the value of user_device.umengid
     *
     * @mbggenerated
     */
    public Long getUmengid() {
        return umengid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.umengid
     *
     * @param umengid the value for user_device.umengid
     *
     * @mbggenerated
     */
    public void setUmengid(Long umengid) {
        this.umengid = umengid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.storeid
     *
     * @return the value of user_device.storeid
     *
     * @mbggenerated
     */
    public Long getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.storeid
     *
     * @param storeid the value for user_device.storeid
     *
     * @mbggenerated
     */
    public void setStoreid(Long storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.usertoken
     *
     * @return the value of user_device.usertoken
     *
     * @mbggenerated
     */
    public String getUsertoken() {
        return usertoken;
    }

    public String getLoginusername() {
		return loginusername;
	}

	public void setLoginusername(String loginusername) {
		this.loginusername = loginusername;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.usertoken
     *
     * @param usertoken the value for user_device.usertoken
     *
     * @mbggenerated
     */
    public void setUsertoken(String usertoken) {
        this.usertoken = usertoken == null ? null : usertoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.devicetoken
     *
     * @return the value of user_device.devicetoken
     *
     * @mbggenerated
     */
    public String getDevicetoken() {
        return devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.devicetoken
     *
     * @param devicetoken the value for user_device.devicetoken
     *
     * @mbggenerated
     */
    public void setDevicetoken(String devicetoken) {
        this.devicetoken = devicetoken == null ? null : devicetoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.appversion
     *
     * @return the value of user_device.appversion
     *
     * @mbggenerated
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.appversion
     *
     * @param appversion the value for user_device.appversion
     *
     * @mbggenerated
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion == null ? null : appversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.logintime
     *
     * @return the value of user_device.logintime
     *
     * @mbggenerated
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.logintime
     *
     * @param logintime the value for user_device.logintime
     *
     * @mbggenerated
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.devicemac
     *
     * @return the value of user_device.devicemac
     *
     * @mbggenerated
     */
    public String getDevicemac() {
        return devicemac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.devicemac
     *
     * @param devicemac the value for user_device.devicemac
     *
     * @mbggenerated
     */
    public void setDevicemac(String devicemac) {
        this.devicemac = devicemac == null ? null : devicemac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.deviceimei
     *
     * @return the value of user_device.deviceimei
     *
     * @mbggenerated
     */
    public String getDeviceimei() {
        return deviceimei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.deviceimei
     *
     * @param deviceimei the value for user_device.deviceimei
     *
     * @mbggenerated
     */
    public void setDeviceimei(String deviceimei) {
        this.deviceimei = deviceimei == null ? null : deviceimei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.devicenote
     *
     * @return the value of user_device.devicenote
     *
     * @mbggenerated
     */
    public String getDevicenote() {
        return devicenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.devicenote
     *
     * @param devicenote the value for user_device.devicenote
     *
     * @mbggenerated
     */
    public void setDevicenote(String devicenote) {
        this.devicenote = devicenote == null ? null : devicenote.trim();
    }
}